name: continuous-integration workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build the server
    defaults:
      run:
        working-directory: ./server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

  test:
    name: Test the server
    defaults:
      run:
        working-directory: ./server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Use private key
        run: echo "${{ secrets.PRIVATE_KEY }}" > private.pem

      - name: Use public key
        run: echo "${{ secrets.PUBLIC_KEY }}" > public.pem
      
      - name: Test
        run: yarn test
